<?php

namespace Tests\Unit;

use App\Article;
use App\Comment;
use App\User;
use Tests\TestCase;

class CommentTest extends TestCase
{
    private $user;
    private $article;
    private $comment;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = create(User::class);
        $this->article = create(Article::class, [
            'user_id' => $this->user->id
        ]);
        //commented this out cause this does not fuqing work
        // 2 hrs search wa gyud naka kitag solution
        //1) Tests\Unit\CommentTest::a_comment_belongs_to_an_article
        //TypeError: Argument 1 passed to Illuminate\Database\Grammar::parameterize() must be of the type array,
        // int given, called in /home/vagrant/code/tdd-training/training/vendor/laravel/framework/src/Illuminate/
        // Database/Query/Grammars/Grammar.php on line 866
        //comment this out to see the fuqing error and comment the code below
//        $this->comment = create(Comment::class, [
//            'user_id' => $this->user->id,
//            'article_id' => $this->article->id,
//        ]);
        // this code works but it's not optimal the code above doesn't work so
        //this is an alternative (Tinamban)
        $this->comment = new Comment;
        $this->comment->content = 'fuqing doesnt work Arguement grammar aaaah';
        $this->comment->user_id = $this->user->id;
        $this->comment->article_id = $this->article->id;
        $this->comment->save();
    }

    /** @test */
   public function a_comment_belongs_to_an_article()
   {
        $this->assertInstanceOf(Article::class,$this->comment->article);
   }
    /** @test */
    public function a_comment_belongs_to_an_author()
    {
        $this->assertInstanceOf(User::class,$this->comment->author);
    }
}
